### ISSUE TITLE
How do I change locale?

### ISSUE THREAD

**Issue by nhtua** [KodiCMS/kodicms-laravel#50]
![screenshot from 2015-06-24 22 52 54](https://cloud.githubusercontent.com/assets/5275627/8334752/c6c4422c-1ac3-11e5-80cf-bb64e7cd6476.png)
After install follow steps of `README.md`, the cms can run but Interface display translation key instead of text in RU or EN. I had run command:
$ php artisan cms:modules:locale:publish
$ php artisan cms:modules:locale:publish --locale=ru
$ php artisan cms:modules:locale:publish --locale=en

and change local in `config/app.php` but the problem not solved.

**Comment by butschster** [comment]
Hi, @nhtua
Unfortunately, KodiCMS dont have english translate now. I need help to translate it to English language.

**Comment by nhtua** [comment]
Dear @butschster ,
I can help translate it to English, but at least, the text must be show in Russian. In the picture, you can see, it shows "i18n key", not Russian text. How do I make it show Russian text? I can translate it if i know exactly where it is appear.

**Comment by butschster** [comment]
Hi
Update repository, (you need commit https://github.com/KodiCMS/kodicms-laravel/commit/6842572ba73396a5602ff3590c350782dcd40c12)

Run command `php artisan cms:modules:locale:publish --locale=en` and locale files will be copied to folder `resources/lang/vendor/`

Uncomment this line https://github.com/KodiCMS/kodicms-laravel/blob/dev/config/cms.php#L55 , clear cache and set English language on user profile page http://laravel.kodicms.ru/backend/user/1/edit

Profit

**Comment by butschster** [comment]
You can ask me question in the chat https://gitter.im/KodiCMS/kodicms-laravel. I help you translate

**Comment by nhtua** [comment]
Thank you so much! I'm translating now. And I have fixed small Case-Sensitive error for run `Artisan` on Linux.
