### ISSUE TITLE
Вынос методов работы с файлами из ModuleLoader

### ISSUE THREAD

**Issue by butschster** [KodiCMS/kodicms-laravel#58]
Сейчас класс ModuleLoder отвечает за поиска файлов внутри модулей и плагинов, что наверно не очень верно. Возможно стоит добавить класс ModulesFileSystem, который будет заниматься всем этим?!

**Comment by greabock** [comment]
Еще там есть файловый хелпер. Хотя в ларе работа с файлами и так неплохо реализована )

**Comment by butschster** [comment]
@greabock ты слишком много зацикливаешься на стандартном функционале Laravel, советую посмотреть то, что содержит мой хелпер, если ты найдешь в стандартном наборе такие методы, я с удовольствием их заменю.
