### ISSUE TITLE
breadcrumb issue

### ISSUE THREAD

**Issue by teodorsandu** [KodiCMS/kodicms-laravel#60]
I couldn't find where to fix this:
![2015-07-24_002124](https://cloud.githubusercontent.com/assets/5700488/8863584/4a90c2e6-319a-11e5-9628-fc13335c00e2.jpg)

**Comment by butschster** [comment]
Hi, thx for this issue.

See https://github.com/KodiCMS/kodicms-laravel/blob/dev/modules/CMS/Http/Controllers/AbstractFileController.php#L82

If you want to translate to english use artisan command `cms:modules:locale:diff --locale=en`
