### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by teodorsandu** [KodiCMS/kodicms-laravel#62]
Hi!

Great CMS, although complicated for me who wants to learn Laravel and the same time build a website with it !

After a fresh installation of kodicms (the latest) the pages are not loaded (/backend/page) instead I get the spinner:

![spinner](https://cloud.githubusercontent.com/assets/5700488/8875347/e94ce2f6-3218-11e5-845a-010d0fc39dbf.jpg)

It seems demo data is populated into database, so I cannot understand what could be the reason:

![pages-exists-in-database](https://cloud.githubusercontent.com/assets/5700488/8875377/134b15f0-3219-11e5-875a-867498591359.jpg)

Appreciate any help!

Thank you

**Comment by butschster** [comment]
Hi, i need to see ajax response (for example from chrome console)

**Comment by teodorsandu** [comment]
Ok I get it, it was because I didn't run it from root (e.g. localhost:8000), but instead from a subfolder:

![ajax-console](https://cloud.githubusercontent.com/assets/5700488/8875740/854bfa00-321b-11e5-8e2c-2bfeeadb5ddf.jpg)

![ajax-from-root](https://cloud.githubusercontent.com/assets/5700488/8875592/a483ce8a-321a-11e5-9534-e98cc9311ea5.jpg)

I suppose doesn't worth to make it work from a subfolder, or it worth?

Sorry, should I have looked before the console :smile: 

Thanks!

**Comment by butschster** [comment]
try to set up in .env file `APP_URL=http://your_host` and clear cache

**Comment by teodorsandu** [comment]
I did it but I think the problem is the path being fixed to root ('/api.updates.check.new_version') in the file \modules\Notifications\resources\js\backendEvents.js

Anyway, that's not important, I can run `php artisan serve` to simulate root, thanks again
