### ISSUE TITLE
Problems installing kodicms

### ISSUE THREAD

**Issue by teodorsandu** [KodiCMS/kodicms-laravel#63]
Hi,

On a fresh install of kodicms I used:

```
git clone https://github.com/KodiCMS/kodicms-laravel.git
cd kodicms-laravel
composer install
php artisan cms:install
```

The database prefix required by module Installer breaks the application:
![2015-07-26_011821](https://cloud.githubusercontent.com/assets/5700488/8891675/de972d68-3334-11e5-947c-c251c3326952.jpg)

Empty string not accepted, I had to enter something('zzz').

Of course table not found because all tables are prefixed by 'zzz'
![2015-07-26_012419](https://cloud.githubusercontent.com/assets/5700488/8891681/3a5e79bc-3335-11e5-9717-42edb26b1260.jpg)

It is really necessary prefixing database tables? And shouldn't be optional, because it seems to be required.

To make database prefix optional I modified (a hack) the file `kodicms-laravel\modules\Installer\Console\Commands\InstallCommand.php`:

```
//['DB_PREFIX', 'pr', InputOption::VALUE_OPTIONAL, 'Database prefix', array_get($defaults, 'DB_PREFIX')],
['DB_PREFIX', 'pr', InputOption::VALUE_NONE, 'Database prefix', null],
```

In the end, I get this error:

![2015-07-26_013455](https://cloud.githubusercontent.com/assets/5700488/8891771/a6dd4eb4-3336-11e5-97b0-08f2481d4425.jpg)

After commenting out `'type' => 'default',` in `kodicms-laravel\modules\Datasource\database\seeds\DatasourceTableSeeder.php` :

```
app()->make(SectionRepository::class)->create([
            //'type' => 'default',
            'name' => 'Test section',
            'description' => 'Test description',
            'is_indexable' => false,
            'created_by_id' => 1,
            'settings' => []
        ]);
```

no error:

![2015-07-26_013922](https://cloud.githubusercontent.com/assets/5700488/8891787/74c7e6fe-3337-11e5-9bf4-d13def25b2ea.jpg)

then `php artisan serve` to run server at `http://localhost:8000/`

Then I logged in successfully with the email and pass provided. But all links are relative to `/localhost/` and not `/localhost:8000/`. I modified in `.env` file `APP_URL=http://localhost:8000`  and  in `config/app/php` too(just in case): 

```
'url' => env('APP_URL', 'http://localhost:8000'),
```

...And after clearing the cache the links are good.

Next step I wanted to switch language to English. In `config/app.php` modified `'locale' => 'en',`  and indeed `http://localhost:8000/backend/auth/login` was in English, but no so after the login (at `http://localhost:8000/backend`).

After that run in console:`php artisan cms:modules:publish` and get:

```
C:\wamp\www\laravel\kodiii\kodicms-laravel>php artisan cms:modules:publish

  [InvalidArgumentException]
  Command "cms:modules:publish" is not defined.
  Did you mean one of these?
      cms:modules:list
      cms:modules:locale:diff
      cms:modules:locale:publish
      cms:modules:migrate
      cms:modules:seed
      ide-helper:models
```

Then running `php artisan cms:modules:locale:publish`:

```
C:\wamp\www\laravel\kodiii\kodicms-laravel>php artisan cms:modules:locale:publish
Copied api:core [C:\wamp\www\laravel\kodiii\kodicms-laravel\modules\API\resources\lang\ru\core.php] To [C:\wamp\www\laravel\kodiii\kodicms-laravel\/resources/lang/vendor\api\en\core.php]
Copied cms:core [C:\wamp\www\laravel\kodiii\kodicms-laravel\modules\CMS\resources\lang\ru\core.php] To [C:\wamp\www\laravel\kodiii\kodicms-laravel\/resources/lang/vendor\cms\en\core.php]
...etc etc
```

meaning it overwrites `kodicms-laravel\/resources/lang/vendor\api\en\core.php` with a russian translation `kodicms-laravel\modules\API\resources\lang\ru\core.php`! Now the only route in English `http://localhost:8000/backend/auth/login` is in Russian!

After that, running `php artisan cms:modules:locale:diff --locale=en` doesn't produce anything in console, or in browser.

Having made a backup copy beforehand of `kodicms-laravel\/resources/lang/vendor\` restored at least the login page in English.

So far the only way I figured out to have the backend in English was to manually copy the files from 

```
kodicms-laravel\/resources/lang/vendor\[module]/en/
```

 to 
~~kodicms-laravel\modules[module]\resources\lang\en~~ (didnt work)

```
kodicms-laravel\modules\[module]\resources\lang\ru
```

Yes, overwriting the Russian files.
I noticed into the source page the locale is still set to `ru`:
![2015-07-26_035926](https://cloud.githubusercontent.com/assets/5700488/8892173/1f02d4b8-334b-11e5-95f0-88f3894e08d2.jpg)

I also tried to modify and save `http://localhost:8000/backend/layouts/edit/normal.blade`, green notification appears on the top-right zone, but get a console error:
![2015-07-26_040529](https://cloud.githubusercontent.com/assets/5700488/8892183/d5252318-334b-11e5-9c1c-89423a4d430b.jpg)
and of course the file `normal.blade.php` was not modified.

Well, a lot I dont understand or I dont do it well... I think it's important for non-russian people in order to contribute to this project to be able to install kodicms-laravel without problems. 
Your project is very promising among all laravel-cms I've seen on github, well done!

Thank you

**Comment by teodorsandu** [comment]
Sorry, I should have logged in with admin_en@site.com  and not with  admin@site.com to get English, my fault!

**Comment by butschster** [comment]
You can change language on user Profile page and global (default language) on the settings page.

KodiCMS has english translate `resources/vendor/...`, but it's no fully translated.

When you run the console command `php artisan cms:modules:locale:diff --locale=en` you see on the left column missed translate keys, on the right column translate keys placement.

For example 

Left column

<pre>
modules\cms\en\system.php
label.settings.profiling_mode: Режим профилирования
</pre>

It means that you need to add translate to the file `resources\lang\vendor\cms\en\system.php` (Right column) the key

<pre>
[
    'label' => [
        ....,
        'settings' => [
            ....,
            'profiling_mode' => 'Profiling mode',
            .....,
        ],
        ....
    ]
]
</pre>

Sorry for my english.

**Comment by butschster** [comment]
Try installer

**Comment by teodorsandu** [comment]
Tested a new fresh installation with cli, works well, no database prefix required, thank you!
