### ISSUE TITLE
Saving from ace

### ISSUE THREAD

**Issue by teodorsandu** [KodiCMS/kodicms-laravel#66]
Hi Pavel,

Saving layouts or snippets (e.g.`http://localhost/backend/layouts/edit/normal.blade` or `http://localhost/backend/snippets/edit/header.blade`) does not work for me. When I click on "Update" button a green notification appears saying the `Layout/Snippet [the name] updated`, but no changes on disk. I even set up this app to work nativelly on root (content of `public` dir moved on my document root: `c:/wamp/www/` and the paths from `index.php` pointing to `c:/wamp/kodi/`), but no luck. No errors in console.
In your demo at http://laravel.kodicms.ru/backend/snippets/edit/content.blade which is editable, saving is working( see `<!-- teodor testing save -->`).
What could be?
Thank you

**Comment by butschster** [comment]
Hi, unfortunately i have the same problem on Windows plaform. I will try to solve this problem

**Comment by butschster** [comment]
Can you test new section in KodiCMS - Datasource?

**Comment by butschster** [comment]
You can edit layout files (`resources/layouts/`) and snippets (`resources/snippets/`) local.

**Comment by butschster** [comment]
Try to save/

**Comment by teodorsandu** [comment]
Wonderful, it works! Now saves layouts and snippets! :) spasibo!

**Comment by teodorsandu** [comment]
How can I test Datasource? It's about downloading/ setting php headers?

**Comment by butschster** [comment]
Datasource - is a new section http://laravel.kodicms.ru/backend/datasource/1, where you can create custom admin sections with custom fields and relations. But now it have only russian traslation, If you want you can try translate it.

**Comment by butschster** [comment]
My skype - butschpavel
