### ISSUE TITLE
Ошибка при деактивация плагина

### ISSUE THREAD

**Issue by SergeyMiracle** [KodiCMS/kodicms-laravel#71]
В списке плагинов не верно работает вкл/выкл, при попытке выключить всплывает окно alert() и даже если нажать "отмена", плагин будет отключен.

**Comment by butschster** [comment]
При включении плагина, если у него есть миграции, система выполнит их.
При выключении плагина система спрашивает удалить ли таблицы из БД, что приведет к удалению всех данных из таблиц. Если нажата отмена, то плагин деактивируется, но при этом таблицы останутся в БД

**Comment by SergeyMiracle** [comment]
Вот как это работает :) Может разделить обязанности - вкл/выкл, удаление бд - на разные кнопы? Если я так затупил, думаю еще найдется народ :D

**Comment by ghost** [comment]
Может закроете? а то висит так себе.
