### ISSUE TITLE
Custom localization

### ISSUE THREAD

**Issue by ghost** [KodiCMS/kodicms-laravel#76]
Хочу добавить динамическую смену локализации для клиента. Нужно добавлять запрос на сохранение в базе?

**Comment by ghost** [comment]
И данные по языку я видел сохраняются в JSON, что допустим если я захочу свои добавить - нужно переделывать всю папку вендор?

**Comment by butschster** [comment]
Что значит динамическую?

**Comment by ghost** [comment]
Ну кнопку на сайте ru en ua

**Comment by butschster** [comment]
Для этого достаточно при смене языка клиенту в сессию заносить текущий язык и в своем модуле или плагине в ServiceProvider в boot добавить Lang::setLocale($locale);

**Comment by butschster** [comment]
либо в папке app

**Comment by butschster** [comment]
JSON только для JS админки используются. Что ты хочешь сделать?

**Comment by ghost** [comment]
Ок услышал) Сделать хочу локализацию в своем модуле. Что бы все текстовые данные в шаблоне вообще не фигурировали.
