### ISSUE TITLE
Ошибка обработки ссылок в nginx

### ISSUE THREAD

**Issue by NanoProto** [KodiCMS/kodicms-laravel#91]
Не корректно ведут себя виджеты на рабочем столе, нельзя переместить, сменить размер и тд.,
нет редакторов. 
тестовая система ngnix, php5-fpm ubuntu-server/
так же не смог прикрутить postgresql, может в будущих версиях прикрутить изначально?

**Comment by butschster** [comment]
Я так понимаю что виртуальные ссылки не обрабатывает nginx в backend. Попробуй перейти по ссылке /backend/cms/js/DashboardController.js

**Comment by NanoProto** [comment]
пробовал, нет файла, сейчас смотрю структуры файлов, где на находится фаил генерирующий head

**Comment by butschster** [comment]
смотри, файлы начинающиеся с /backend/ отдаются через контроллер по виртуальному пути, желательно для backend отключить кеширование отдачи файлов

**Comment by li4i** [comment]
подскажешь как это сделать, отключить кеш

**Comment by butschster** [comment]
да, ближе к вечеру

**Comment by butschster** [comment]
Можешь прислать свой конфиг?

**Comment by butschster** [comment]
@li4i Привет, разобрался с проблемой?

Я сегодня смотрел конфиг nginx и 

Вот пример того, как выглядит кеширование media файлов

```
location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|js|cur|swf)$ {
     root     /path/to/document/root/;
     expires  7d;
}
```

В моем случае, я запретил кеширование для урл, содержащих `/backend/`

```
location ~* ^((?!\/backend\/).)*\.(jpg|jpeg|gif|png|ico|css|js|cur|swf)$ {
        root     /path/to/document/root/;
        expires  7d;
}
```
