### ISSUE TITLE
Проблемы при установке

### ISSUE THREAD

**Issue by ASM-Development** [KodiCMS/kodicms-laravel#92]
```
git clone https://github.com/KodiCMS/kodicms-laravel.git
cd kodicms-laravel
composer install
php artisan cms:install
```

```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "cms:install" is not defined.
  Did you mean one of these?
      migrate:install
      cms:make:controller
      cms:modules:publish
      cms:modules:install
      cms:modules:locale:diff
      cms:wysiwyg:list
      cms:modules:locale:publish
      cms:plugins:activate
      cms:plugins:deactivate
      cms:api:generate-key
      cms:generate:translate:js
      cms:plugins:list
```

Платформа: Windows

**Comment by ASM-Development** [comment]
[log.txt](https://github.com/KodiCMS/kodicms-laravel/files/168787/log.txt)

**Comment by butschster** [comment]
Привет, инструкция устарела немного, только что исправил.
- Клонировать репозиторий _(Clone repository)_ `git clone https://github.com/KodiCMS/kodicms-laravel.git`
- Запустить команду _(Run command)_ `composer install` для загрузки всех необходимых компонентов
- Скопировать .env.example в .env и настроить подключение к БД, затем выполнить комманду _(Copy .env.example and rename to .env. Configure database connection, then run artisan command)_ `php artisan modules:migrate --seed`
- Сгенерировать application ключ `php artisan key:generate`
- Выполнить установку системы _(Install CMS)_ `php artisan cms:modules:install`.

**Comment by ASM-Development** [comment]
странно, но пришлось запилить

```
CACHE_DRIVER=file
```

в остальном всё работает

**Comment by butschster** [comment]
А что стояло по умолчанию?

**Comment by butschster** [comment]
Какая ошибка с `sqlite`?

**Comment by butschster** [comment]
Проблемы с кешем исправил.
