### ISSUE TITLE
Ошибка в дате последнего визита

### ISSUE THREAD

**Issue by Dualse** [KodiCMS/kodicms-laravel#93]
Когда в админке смотришь профиль пользователя, то в дате последнего визита находится некорректная информация.
![- admin arvik telecom - google chrome](https://cloud.githubusercontent.com/assets/10233576/13879328/1ba1dbec-ed41-11e5-8be3-18878797e2f1.png)

**Comment by butschster** [comment]
https://github.com/KodiComponents/module-users/releases/tag/v0.0.8
