### ISSUE TITLE
При сидинги выбрасывает ошибку

### ISSUE THREAD

**Issue by Dualse** [KodiCMS/kodicms-laravel#96]
После установки, когда пишешь свой модуль и пытаешься сделать сидинг, то появляется ошибка:
![-terminal](https://cloud.githubusercontent.com/assets/10233576/14403670/b28c00e4-fe82-11e5-9817-d94f80f00317.png)
Приходится комментировать код в UsersTableSeeder, чтобы выполнить сидинг.
![-terminal-1](https://cloud.githubusercontent.com/assets/10233576/14403684/208db04c-fe83-11e5-9c56-679d9ab0c31b.png)

**Comment by butschster** [comment]
Да, вижу проблему.

Необходимо в `RolesTableSeeder` добавить `DB::table('roles_users')->truncate();`
