### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by ODDsama** [KodiCMS/kodicms-laravel#97]
Сначала была ошибка не хотело проводить composer install поборол удалив запуск скриптов в composer.json
Но теперь получаю такую ошибку постоянно, что в браузере, что в консоли. Чтобы я не пытался сделать, толи зайти, толи artisan команду запустить.
`
Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php:738 Stack trace: #0 E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php(738): ReflectionClass->__construct('log') #1 E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php(633): Illuminate\Container\Container->build('log', Array) #2 E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('log', Array) #3 E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php(853): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...') #4 E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter) in E:\Work\OpenServer\domains\rus.kodi\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 738`

**Comment by CrazyRedScorp** [comment]
И снова я. С прискорбием спешу сообщить что ошибка тоже имеется, правда немного другого характера

```
# git clone https://github.com/KodiCMS/kodicms-laravel.git
Cloning into 'kodicms-laravel'...
remote: Counting objects: 23927, done.
remote: Total 23927 (delta 0), reused 0 (delta 0), pack-reused 23927
Receiving objects: 100% (23927/23927), 20.12 MiB | 835.00 KiB/s, done.
Resolving deltas: 100% (10812/10812), done.
#
# cd kodicms-laravel
#
# composer install
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> php artisan clear-compiled
PHP Warning:  require(/var/www/html/kodicms-laravel/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/kodicms-laravel/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/kodicms-laravel/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/kodicms-laravel/bootstrap/autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

[RuntimeException]
  Error Output: PHP Warning:  require(/var/www/html/kodicms-laravel/bootstrap/../vendor/autoload.php): failed to open stream: No such file or director
  y in /var/www/html/kodicms-laravel/bootstrap/autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required '/var/www/html/kodicms-laravel/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pe
  ar:/usr/share/php') in /var/www/html/kodicms-laravel/bootstrap/autoload.php on line 17
```

Удаляем только один скрипт!

```
    "pre-update-cmd": [
      "php artisan clear-compiled"
    ],
```

И запускаем повторно, в итоге вроде все собирается, выполняем дальнейшие рекомендации. Однако есть пару "но":
1. `php artisan modules:migrate --seed` пришлось выполнить второй раза (после полной инсталляции), почему-то с первого раза ложатся только 5 таблиц `api_keys cache config migrations sessions`
2. для *nix систем обязательно выполнить `chown` с нужными правами, иначе будет в логах ошибка типа `access denied`.

В папке public имеем следующее:

```
> assets
> cms
.htaccess
index.php
robots.txt
```

В итоге пустой сайт (без контента, просто пару полосок) открывается по ссылке `http://<you_host>/kodicms-laravel/server.php`
Посмотрим что же нам говорит дебагер браузера, опаньки:

```
GET http://<you_host>/kodicms-laravel/server.php/cms/libs/jquery/js/jquery.min.js      server.php:7
Uncaught Error: Bootstrap's JavaScript requires jQuery(anonymous function)    bootstrap.min.js:6
GET http://<you_host>/kodicms-laravel/server.php/cms/favicon.ico 500 (Internal Server Error)   favicon.ico:1
```

При открытии ссылки `http://<you_host>/kodicms-laravel/public/` проблем в браузере нет, но все равно на экране пусто. Дебагер браузера же говорит что тут что-то есть:

```
<body>
    <div class="container">
        <div class="header clearfix">
                    </div>
        <div class="row">
            <div class="col-md-4">
                            </div>
            <div class="col-md-8">
                            </div>
        </div>
        <footer class="footer">
                    </footer>
    </div>
</body>
```

Да и в админку доступа пока нема. При попытке открыть `http://<you_host>/kodicms-laravel/public/backend` ловим редирект на `http://<you_host>/backend`, `а http://<you_host>/kodicms-laravel/backend` сваливается на 404.

**Comment by butschster** [comment]
По поводу установки Laravel версии да, нужно будет композер немного подправить.

При добавлении виртуального хоста в апаче необходимо выбирать папку public, а не корень kodicms и тогда все заработает как надо.

Пиши по проблемам в https://gitter.im/KodiCMS/kodicms-laravel

**Comment by CrazyRedScorp** [comment]
Проблема с доступом к сайту и в админ часть решается путем добавления httpd.conf следующей ветки:

```
<Directory "/var/www/kodicms-laravel">  <-путь к папке где лежит папка public (но не к ней самой!)
    Options Indexes FollowSymLinks
    AllowOverride All <- вот этот параметр обязательно должен быть!!!
    Require all granted
</Directory>
```
